// <auto-generated />
using System;
using CSE443_KTM_Ecommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSE443_KTM_Ecommerce.Migrations
{
    [DbContext(typeof(KTMDbContext))]
    [Migration("20250609144609_ProductImageSeedData")]
    partial class ProductImageSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double?>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(8908),
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(8919),
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(8920),
                            Name = "Jacket"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(8921),
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CouponCount")
                        .HasColumnType("int");

                    b.Property<decimal>("CouponMaxSpend")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CouponMinSpend")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CouponStatus")
                        .HasColumnType("int");

                    b.Property<int>("CouponType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DeliveryFees")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Deliveries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryFees = 2.99m,
                            Description = "Delivered in 3–5 days",
                            Name = "Standard Delivery"
                        },
                        new
                        {
                            Id = 2,
                            DeliveryFees = 5.99m,
                            Description = "Delivered in 1–2 days",
                            Name = "Express Delivery"
                        },
                        new
                        {
                            Id = 3,
                            DeliveryFees = 1.02m,
                            Description = "Pick up from store for free",
                            Name = "Pickup In-Store"
                        });
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CouponId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<double>("OrderTotalPrice")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fabric")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Featured")
                        .HasColumnType("bit");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoldQuantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Warranty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "manchesterunited",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(8935),
                            Description = "Captain Marvel’s jersey: number 7 for Bryan Robson, United’s longest-serving captain (1982–1994) with 461 appearances. This one-to-one adidas remake celebrates the 1991 Cup Winners’ Cup triumph, featuring detailed cuffs, collar, subtle patterns, and the special cup final badge in classic white away colors.",
                            Dimensions = "36 x 26 x 3 cm",
                            Fabric = "jacquard",
                            Featured = true,
                            Name = "Manchester United x adidas Bring Back 1991 Away 7 Printed Jersey White",
                            Price = 160.00m,
                            ProductTypeId = 1,
                            Quantity = 25,
                            Size = "XS, S, M, L, XL, 2XL, 3XL",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "6 months",
                            Weight = "0.32 kg"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "manchesterunited",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(8944),
                            Description = "Relive the early Premier League glory with this Manchester United retro shirt, worn in the 92/93 and 93/94 title-winning seasons. Featuring bold United red and a white contrast collar, it’s perfect for fans celebrating club legends or adding a stylish 90s vibe to their look.",
                            Dimensions = "35 x 25 x 3 cm",
                            Fabric = "polyester",
                            Featured = true,
                            Name = "Manchester United 1992-94 Retro Home Shirt Red",
                            Price = 100.00m,
                            ProductTypeId = 1,
                            Quantity = 50,
                            Size = "S, M, L, XL, 2XL",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "6 months",
                            Weight = "0.30 kg"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "manchesterunited",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(8946),
                            Description = "Manchester United at Old Trafford: beloved by fans, respected by rivals. The 24/25 home jersey stands out with bright red side inserts and a subtle gradient design. Made for supporters, it features adidas AEROREADY, an embroidered badge, and 100% recycled materials to help reduce waste and environmental impact.",
                            Dimensions = "34 x 24 x 3 cm",
                            Fabric = "polyester",
                            Featured = true,
                            Name = "Manchester United 24/25 Home Jersey",
                            Price = 80.00m,
                            ProductTypeId = 1,
                            Quantity = 130,
                            Size = "M, L, XL, 2XL, 3XL",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "6 months",
                            Weight = "0.28 kg"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "realmadrid",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(8948),
                            Description = "Relive Real Madrid’s 99/00 European triumph with this one-to-one adidas replica of the iconic home jersey. Featuring a Henley collar, classic loose fit, historic TEKA sponsor, and era-specific woven badge, it’s a perfect piece for devoted fans and football fashion lovers.",
                            Dimensions = "35 x 25 x 3 cm",
                            Fabric = "polyester",
                            Featured = true,
                            Name = "Real Madrid Home Bring Back 99/00 Jersey White",
                            Price = 140.00m,
                            ProductTypeId = 1,
                            Quantity = 30,
                            Size = "XS, S, M, L, XL",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "6 months",
                            Weight = "0.31 kg"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "realmadrid",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(8950),
                            Description = "Inspired by Madrid’s “chulapo” outfits, this Real Madrid home jersey features a stylish houndstooth pattern, ventilating HEAT.RDY, and a heat-applied badge. Designed for on-pitch performance, it’s made from 100% recycled materials to help reduce waste and environmental impact.",
                            Dimensions = "34 x 24 x 3 cm",
                            Fabric = "polyester",
                            Featured = true,
                            Name = "Real Madrid Home Authentic Shirt 24/25 White",
                            Price = 100.00m,
                            ProductTypeId = 1,
                            Quantity = 110,
                            Size = "S, M, L, XL, 2XL",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "6 months",
                            Weight = "0.29 kg"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "barcelona",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(8952),
                            Description = "FC Barcelona 2000/01 Retro Nike Jersey: features commemorative collab woven label, embroidered Swoosh and retro FCB crest, printed skeleton graphic on front, plus Cactus Jack spray logo, CJ classic logo, #2, and Barça motif on back.",
                            Dimensions = "37 x 27 x 3 cm",
                            Fabric = "polyester",
                            Featured = true,
                            Name = "CJ X Nike X FC Barcelona Retro 2000/01 Home Skeleton Jersey",
                            Price = 200.00m,
                            ProductTypeId = 1,
                            Quantity = 5,
                            Size = "XS, S, M, L, XL, 2XL, 3XL",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "6 months",
                            Weight = "0.35 kg"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "barcelona",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(8955),
                            Description = "Limited edition of 1,899, this CJ x Nike x FCB men’s athletic-fit jersey comes in a custom collector’s box with a numbered certificate of authenticity. Made with Nike Dri-FIT ADV performance material, it features Cactus Jack, Nike, and FCB logo details.",
                            Dimensions = "36 x 26 x 3 cm",
                            Fabric = "polyester",
                            Featured = true,
                            Name = "FC Barcelona 2024/25 Match Home X Cactus Jack Jersey",
                            Price = 150.00m,
                            ProductTypeId = 1,
                            Quantity = 4,
                            Size = "S, M, L, XL, 2XL",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "6 months",
                            Weight = "0.33 kg"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "acmilan",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(8957),
                            Description = "The 25/26 AC Milan Home Kit turns up the heat with iconic Red & Black, flame-detailed stripes, and a bold red crest. A modern take on the founders’ vision: red like flames, black like fear. Rossoneri, bring the heat.",
                            Dimensions = "35 x 25 x 3 cm",
                            Fabric = "polyester",
                            Featured = true,
                            Name = "AC Milan Home Authentic 2025/26 JERSEY",
                            Price = 163.00m,
                            ProductTypeId = 1,
                            Quantity = 110,
                            Size = "XS, S, M, L, XL, 2XL",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "6 months",
                            Weight = "0.34 kg"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "acmilan",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(8958),
                            Description = "From 1963 to forever. Co-created by PUMA, AC Milan, and Off-White™, this jersey honors Milan’s first European Cup triumph and a world driven by progress. With two alternative colorways and signature Off-White™ details, it celebrates unity and reminds us: change is unstoppable, so dream on.",
                            Dimensions = "34 x 24 x 3 cm",
                            Fabric = "polyester",
                            Featured = true,
                            Name = "AC Milan x OFF-WHITE™ Replica Jersey Men",
                            Price = 150.00m,
                            ProductTypeId = 1,
                            Quantity = 15,
                            Size = "M, L, XL, 2XL, 3XL",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "6 months",
                            Weight = "0.31 kg"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "bayern",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(8987),
                            Description = "The official Bayern München Authentic Away Jersey for the 2025/26 season combines cutting-edge performance with classic club pride. Featuring a gestickt (embroidered) Bayern crest and adidas logo, this jersey is crafted with atmungsaktiv (breathable) materials for ultimate comfort on and off the pitch. Designed for elite performance, it showcases premium adidas engineering and unmistakable Bayern style.",
                            Dimensions = "36 x 26 x 3 cm",
                            Fabric = "polyester",
                            Featured = true,
                            Name = "Bayern Muchen Authentic Away Jersey 25-26",
                            Price = 130.00m,
                            ProductTypeId = 1,
                            Quantity = 130,
                            Size = "S, M, L, XL, 2XL, 3XL",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "6 months",
                            Weight = "0.33 kg"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "psg",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(8988),
                            Description = "The PSG Home Kit 2024/25 delivers a fresh take on the classic Hechter design, inspired by the urban art of Greater Paris. Featuring the iconic central red band framed by thin white brushstroke-style lines, this modern jersey captures the bold, disruptive spirit of a club known as the team of the new generation.",
                            Dimensions = "34 x 24 x 3 cm",
                            Fabric = "polyester",
                            Featured = true,
                            Name = "PSG Nike Home Stadium Shirt 2024-25",
                            Price = 85.00m,
                            ProductTypeId = 1,
                            Quantity = 120,
                            Size = "S, M, L, XL",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "6 months",
                            Weight = "0.28 kg"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "intermilan",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(8990),
                            Description = "For the first time, the second star shines above the logo on the 2024/25 Home Kit. Part of the Match collection, this jersey features Nike Dri-FIT ADV technology, combining lightweight, quick-drying, and breathable fabric for maximum comfort on the pitch. Made from recycled polyester and crafted with athlete-tested design, it’s the exact kit worn by the stars. Customize it with your favorite player’s name, number, and add Lega Serie A 2024/25 or Champions League sleeve patches.",
                            Dimensions = "35 x 25 x 3 cm",
                            Fabric = "polyester",
                            Featured = true,
                            Name = "Inter Milan Nike Home Match Jersey 2024/25",
                            Price = 130.00m,
                            ProductTypeId = 1,
                            Quantity = 110,
                            Size = "M, L, XL, 2XL, 3XL",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "6 months",
                            Weight = "0.32 kg"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "dortmund",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(8992),
                            Description = "A true classic! The Borussia Dortmund 24/25 home shirt features a timeless design with black sleeves and four thin stripes across the iconic yellow base. On the back, bold black “Dortmund” lettering stands out, complemented by subtle stripes running from front to back. The club motto, Borussia verbindet (Borussia unites), is delicately placed on the collar, completing this elegant look.",
                            Dimensions = "33 x 23 x 3 cm",
                            Fabric = "polyester",
                            Featured = true,
                            Name = "Borussia Dortmund 24/25 Home Jersey",
                            Price = 65.00m,
                            ProductTypeId = 1,
                            Quantity = 140,
                            Size = "S, M, L, XL",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "6 months",
                            Weight = "0.27 kg"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "nike",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(8994),
                            Description = "Want to elevate your speed? These Academy Shoes feature an upgraded heel Air Zoom unit, delivering the explosive, propulsive feel you — and Kylian Mbappé — need to break past defenders. The most responsive Mercurial yet, built to help you control pace and tempo all match long.",
                            Dimensions = "30 x 10 x 12 cm",
                            Fabric = "Synthetic Flyknit upper with mesh",
                            Featured = true,
                            Name = "Nike Mercurial Vapor 16 Academy 'Kylian Mbappé'",
                            Price = 110.00m,
                            ProductTypeId = 1,
                            Quantity = 20,
                            Size = "39, 40, 41, 42, 43, 44, 45",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "220g (per shoe, size 42)"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "nike",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(8995),
                            Description = "Looking to elevate your speed? These Academy Shoes feature an enhanced heel Air Zoom unit, giving you — and Kylian Mbappé — the explosive push to break through defenses. It’s the most responsive Mercurial we’ve ever created, built to help you control pace and tempo all match long.",
                            Dimensions = "31 x 10 x 13 cm",
                            Fabric = "Flyknit upper, synthetic overlays",
                            Featured = true,
                            Name = "Nike Mercurial Superfly 10 Academy 'Kylian Mbappé'",
                            Price = 130.00m,
                            ProductTypeId = 1,
                            Quantity = 18,
                            Size = "39, 40, 41, 42, 43, 44, 45",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "230g (per shoe, size 42)"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "nike",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(8998),
                            Description = "Looking to take your game to the next level? The Phantom GX 2 Academy helps put you in prime position of the goal, whether you're the playmaker, assister or finisher. The rest is up to you. Created with goals in mind, NikeSkin covers the striking area of the shoe, while sticky traction helps guide your unscripted agility on the turf.",
                            Dimensions = "30 x 10 x 12 cm",
                            Fabric = "Synthetic NikeSkin upper, rubber outsole",
                            Featured = true,
                            Name = "Nike Phantom GX 2 Academy",
                            Price = 100.00m,
                            ProductTypeId = 1,
                            Quantity = 90,
                            Size = "39, 40, 41, 42, 43, 44, 45",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "240g (per shoe, size 42)"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "adidas",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9000),
                            Description = "Find your fast and express yourself on the pitch with adidas F50 boots, built for pure speed. Featuring a thin Fibertouch upper, Compression Fit Tunnel Tongue for secure lockdown, and Sprintweb 3D texture for close control, these Elite boots deliver. The Sprintframe 360 outsole adds spring and support, keeping you unstoppable on dry grass pitches.",
                            Dimensions = "31 x 11 x 12 cm",
                            Fabric = "Fibertouch synthetic upper, Sprintframe outsole",
                            Featured = true,
                            Name = "Adidas F50 Elite Firm Ground Boots",
                            Price = 200.00m,
                            ProductTypeId = 1,
                            Quantity = 70,
                            Size = "38, 39, 40, 41, 42, 43, 44, 45",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "210g (per shoe, size 42)"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "adidas",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9001),
                            Description = "Discover the difference between hoping to score and knowing you will with adidas Predator boots, built for goals. These League boots feature a Hybridfeel upper with all-over 3D texture and grippy Strikescale fins for precise ball control. A lug rubber outsole ensures stability on artificial turf pitches.",
                            Dimensions = "30 x 11 x 12 cm",
                            Fabric = "Hybridfeel synthetic upper, rubber outsole",
                            Featured = true,
                            Name = "Adidas Predator League Turf Boots",
                            Price = 95.00m,
                            ProductTypeId = 1,
                            Quantity = 100,
                            Size = "38, 39, 40, 41, 42, 43, 44, 45",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "260g (per shoe, size 42)"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "adidas",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9003),
                            Description = "Push your pace to the limit with lightweight adidas F50 boots, engineered for pure speed. Featuring an eye-catching Sprintgrid print, the Fiberskin upper and adaptive Tunnel Tongue provide a secure fit. Underfoot, the Sprintplate 360 outsole delivers extra acceleration on firm ground and artificial grass. Made with at least 20% recycled materials to help reduce waste and environmental impact.",
                            Dimensions = "31 x 11 x 12 cm",
                            Fabric = "Fiberskin synthetic upper, Sprintplate outsole",
                            Featured = true,
                            Name = "Adidas F50 League Firm/Multi-Ground Boots",
                            Price = 90.00m,
                            ProductTypeId = 1,
                            Quantity = 90,
                            Size = "38, 39, 40, 41, 42, 43, 44, 45",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "220g (per shoe, size 42)"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "adidas",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9005),
                            Description = "Feel the rush of speed in the Adizero Evo SL. Inspired by the record-breaking innovation of the Adizero Pro Evo 1, this shoe blends race-day performance with everyday style. Featuring LIGHTSTRIKE PRO foam for responsive cushioning and energy return, it’s built to move—whether you are running or just living life in the fast lane.",
                            Dimensions = "29 x 10 x 11 cm",
                            Fabric = "Primeknit upper, LIGHTSTRIKE PRO foam midsole",
                            Featured = true,
                            Name = "Adizero Evo SL Men",
                            Price = 190.00m,
                            ProductTypeId = 8,
                            Quantity = 60,
                            Size = "40, 41, 42, 43, 44, 45, 46",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "180g (per shoe, size 42)"
                        },
                        new
                        {
                            Id = 21,
                            Brand = "adidas",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9007),
                            Description = "The Ultraboost 5 is built for your most energized run yet. Featuring Light BOOST V2—adidas’ highest energy return cushioning—it delivers unmatched comfort with less weight. A PRIMEKNIT upper adapts to your foot for a perfect fit, while the moulded heel support and Torsion System provide stability and smooth transitions. Finished with a Continental™ outsole for superior grip, this is performance at its peak.",
                            Dimensions = "30 x 11 x 12 cm",
                            Fabric = "Primeknit upper, BOOST midsole, Continental rubber outsole",
                            Featured = true,
                            Name = "Adidas Ultraboost 5",
                            Price = 200.00m,
                            ProductTypeId = 8,
                            Quantity = 70,
                            Size = "40, 41, 42, 43, 44, 45, 46",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "310g (per shoe, size 42)"
                        },
                        new
                        {
                            Id = 22,
                            Brand = "manchesterunited",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9008),
                            Description = "Button up this loose-fitting Manchester United jacket to celebrate Chinese New Year in style. Featuring a golden crest and the iconic devil symbol, it’s a bold way to show your club pride during the festivities. Made with a smooth plain weave shell and soft single jersey lining, this adidas jacket offers all-day comfort. Designed with UNITEFIT, an all-gender fit system created for diverse sizes and shapes, it’s perfect for everyone.",
                            Dimensions = "60x40x5 cm",
                            Fabric = "plain weave shell, single jersey lining",
                            Featured = true,
                            Name = "Manchester United x adidas Chinese New Year Jacket Black",
                            Price = 200.00m,
                            ProductTypeId = 1,
                            Quantity = 120,
                            Size = "XS, S, M, L, XL, 2XL, 3XL",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "850"
                        },
                        new
                        {
                            Id = 23,
                            Brand = "manchesterunited",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9010),
                            Description = "An ode to football history, this Manchester United track top blends iconic club details with adidas archive-inspired style. Its loose fit and smooth fabric keep you comfortable while you represent. The chest features a classic Trefoil alongside a red devil badge, capturing the spirit of the beautiful game. Made with at least 70% recycled materials, it helps reduce waste and environmental impact.",
                            Dimensions = "58x38x4 cm",
                            Fabric = "polyester blend with recycled content",
                            Featured = true,
                            Name = "Manchester United Originals Track Top",
                            Price = 160.00m,
                            ProductTypeId = 1,
                            Quantity = 150,
                            Size = "S, M, L, XL, 2XL",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "700"
                        },
                        new
                        {
                            Id = 24,
                            Brand = "acmilan",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9014),
                            Description = "Rooted in AC Milan’s history, this collection blends the club’s iconic devil mascot and classic red and black with vintage football and “125” anniversary graphics, accented in gold to honor its legacy. Featuring Off-White™ silhouettes for adults and kids—including varsity jackets, hoodies, and tees—plus accessories like caps, scarves, luggage, and socks. Entirely conceptualized and designed in Milan, the varsity jacket is Made in Italy with premium craftsmanship and gold-satin embroidery, celebrating both AC Milan and Off-White™ heritage.",
                            Dimensions = "65x45x6 cm",
                            Fabric = "cotton blend with satin embroidery",
                            Featured = true,
                            Name = "AC Milan X Off-White- Varsity Jacket",
                            Price = 2950.00m,
                            ProductTypeId = 1,
                            Quantity = 40,
                            Size = "M, L, XL, 2XL",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "24 months",
                            Weight = "1200"
                        },
                        new
                        {
                            Id = 25,
                            Brand = "realmadrid",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9015),
                            Description = "Comfort meets fandom in this adidas training jacket, perfect for showing your Real Madrid pride at the stadium or from home. Ribbed details and soft jersey fabric deliver a cozy fit, while the embroidered club logo and classic white-and-blue colors make your allegiance clear.",
                            Dimensions = "59x39x4 cm",
                            Fabric = "jersey fabric with ribbed trims",
                            Featured = true,
                            Name = "Real Madrid Adidas DNA Track Top 24/25 White",
                            Price = 100.00m,
                            ProductTypeId = 1,
                            Quantity = 180,
                            Size = "S, M, L, XL, 2XL",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "750"
                        },
                        new
                        {
                            Id = 26,
                            Brand = "intermilan",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9017),
                            Description = "The pre-match INTER anthem jacket is the same one worn by your favourite players when they take to the pitch during big Champions League nights. Perfect to wear over your jersey, it provides ideal warmth as you cheer on the Nerazzurri.",
                            Dimensions = "60x40x5 cm",
                            Fabric = "polyester with mesh lining",
                            Featured = true,
                            Name = "Inter Milan Nike Pre-Match Champions League Anthem Jacket",
                            Price = 130.00m,
                            ProductTypeId = 1,
                            Quantity = 140,
                            Size = "S, M, L, XL, 2XL, 3XL",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "800"
                        },
                        new
                        {
                            Id = 27,
                            Brand = "psg",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9018),
                            Description = "Made in Italy, the Jordan Wings x PSG Varsity Jacket blends premium materials with timeless sport style. Featuring a cashmere-blend body, leather shoulder panels in a wing-inspired design, and an allover embroidered ICI C’EST PARIS monogram, it’s finished with a matching satin lining and ribbed cuffs and collar. Available in Blue Void, this jacket delivers a truly standout look.",
                            Dimensions = "66x46x6 cm",
                            Fabric = "cashmere blend with leather panels",
                            Featured = true,
                            Name = "PSG x Jordan Wings Cashmere and Leather Varsity Jacket - Blue Void",
                            Price = 2100.00m,
                            ProductTypeId = 1,
                            Quantity = 50,
                            Size = "M, L, XL",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "24 months",
                            Weight = "1400"
                        },
                        new
                        {
                            Id = 28,
                            Brand = "manchesterunited",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9020),
                            Description = "Show your United pride with this official bucket hat, inspired by the design gifted at the 22/23 FA Cup final and revived by fans during the 23/24 celebrations. Featuring bar stripes in fan flag colours and an embroidered devil on the visor, it’s a timeless accessory for true supporters. Made from soft cotton twill for all-day comfort.",
                            Dimensions = "30x30x15 cm",
                            Fabric = "cotton twill",
                            Featured = true,
                            Name = "Manchester United x New Era Bar Stripe Bucket Hat",
                            Price = 30.00m,
                            ProductTypeId = 2,
                            Quantity = 200,
                            Size = "S, M, L",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "150"
                        },
                        new
                        {
                            Id = 29,
                            Brand = "manchesterunited",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9022),
                            Description = "Perfect for young fans, this Fred the Red plush is a fun matchday companion or a charming addition to any United-themed room. Dressed in a bucket hat and red devil tee, this mascot toy sports a classic fan look—bringing Manchester United style and spirit home. A great gift for supporters of all ages.",
                            Dimensions = "20x15x15 cm",
                            Fabric = "plush fabric",
                            Featured = true,
                            Name = "Manchester United Bucket Hat Fred the Red Plush Red",
                            Price = 25.00m,
                            ProductTypeId = 3,
                            Quantity = 150,
                            Size = "One Size",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "300"
                        },
                        new
                        {
                            Id = 30,
                            Brand = "manchesterunited",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9023),
                            Description = "A stylish gift for any Manchester United fan, this official scarf pairs effortlessly with any outfit while adding a subtle nod to the club. Featuring a sleek black design with white and gold stripes, it’s finished with gold embroidered devils to show your allegiance. Packaged in a premium gift box, it’s the perfect present for the Reds in your life.",
                            Dimensions = "180x25x5 cm",
                            Fabric = "acrylic blend",
                            Featured = true,
                            Name = "Manchester United Bar Scarf Gift Box Black",
                            Price = 20.00m,
                            ProductTypeId = 4,
                            Quantity = 250,
                            Size = "One Size",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "250"
                        },
                        new
                        {
                            Id = 31,
                            Brand = "manchesterunited",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9025),
                            Description = "Bring Old Trafford to life with this BRXLZ stadium kit, a must-have for any Manchester United fan. Recreate the iconic Sir Alex Ferguson Stand and experience the magic of the Theatre of Dreams piece by piece. Perfect for model builders or newcomers alike, this detailed kit makes a great gift—and a proud display of your United loyalty once complete.",
                            Dimensions = "35x30x15 cm",
                            Fabric = "plastic bricks",
                            Featured = true,
                            Name = "Manchester United BRXLZ Large Old Trafford Stadium",
                            Price = 110.00m,
                            ProductTypeId = 3,
                            Quantity = 100,
                            Size = "One Size",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "1200"
                        },
                        new
                        {
                            Id = 32,
                            Brand = "manchesterunited",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9027),
                            Description = "Add a distinctive piece to your collection with this official Manchester United illustrated football. Featuring detailed line drawings by Manchester artist Izzy Winter, the design showcases iconic views of Old Trafford, the city, and club legends. A size 5 ball, it’s perfect as a display piece or a thoughtful keepsake for any devoted fan.",
                            Dimensions = "22x22x22 cm",
                            Fabric = "synthetic leather",
                            Featured = true,
                            Name = "Manchester United Size 5 Illustrated Football White",
                            Price = 100.00m,
                            ProductTypeId = 1,
                            Quantity = 180,
                            Size = "Size 5",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "450"
                        },
                        new
                        {
                            Id = 33,
                            Brand = "manchesterunited",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9029),
                            Description = "The perfect finishing touch for any young fan’s outfit, this classic kids’ baseball cap features the iconic Manchester United crest for a bold show of team pride. Made from breathable cotton twill with a low crown and adjustable D-ring closure, it offers all-day comfort and effortless summer style. A must-have for every junior Red.",
                            Dimensions = "28x28x12 cm",
                            Fabric = "cotton twill",
                            Featured = true,
                            Name = "Manchester United x New Era Kids 9Forty Core Cap",
                            Price = 26.00m,
                            ProductTypeId = 2,
                            Quantity = 220,
                            Size = "Kids",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "120"
                        },
                        new
                        {
                            Id = 34,
                            Brand = "manchesterunited",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9031),
                            Description = "Relive the rise of a football icon in Wayne Rooney: Teenage Kicks. From his early days at Everton to his record-breaking years at Manchester United, this biography explores the key moments of Rooney’s legendary career. Packed with era-defining highlights and behind-the-scenes stories, it’s a must-read for fans eager to learn more about one of football’s greatest talents—a perfect gift for any United supporter.",
                            Dimensions = "20x13x3 cm",
                            Fabric = "paper",
                            Featured = true,
                            Name = "Wayne Rooney, Teenage Kicks Book",
                            Price = 26.00m,
                            ProductTypeId = 5,
                            Quantity = 300,
                            Size = "One Size",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "No warranty",
                            Weight = "350"
                        },
                        new
                        {
                            Id = 35,
                            Brand = "adidas",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9033),
                            Description = "From daily workouts to game day, these adidas crew-length socks are built for comfort and support. With targeted arch compression and cushioning at the heels and toes, they reduce pressure so you can stay focused on your performance—whether you're training, lifting, or playing.",
                            Dimensions = "25x10x5 cm",
                            Fabric = "cotton blend",
                            Featured = true,
                            Name = "Cushioned Crew Socks 3 Pairs",
                            Price = 10.00m,
                            ProductTypeId = 6,
                            Quantity = 500,
                            Size = "S, M, L",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "6 months",
                            Weight = "90"
                        },
                        new
                        {
                            Id = 36,
                            Brand = "adidas",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9034),
                            Description = "The backpack is back—and better than ever. This adidas classic blends style and function, with space for everything from your laptop to your gym gear. A side pocket keeps your water bottle within easy reach, while its clean design makes it a go-to for daily use.",
                            Dimensions = "45x30x15 cm",
                            Fabric = "polyester",
                            Featured = true,
                            Name = "Classic Badge Of Sport Backpack",
                            Price = 25.00m,
                            ProductTypeId = 7,
                            Quantity = 150,
                            Size = "One Size",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "900"
                        },
                        new
                        {
                            Id = 37,
                            Brand = "adidas",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9036),
                            Description = "Sharpen your skills with adidas Predator Training goalkeeper gloves. Designed for reliable grip and comfort, they feature a cushioned Soft Grip latex palm, flexible backhand, and a roomy finger cut for confident saves. An adjustable elastic bandage strap ensures a secure, stable fit so you can focus on every shot.",
                            Dimensions = "25x15x5 cm",
                            Fabric = "latex and polyester",
                            Featured = true,
                            Name = "Predator Training Goalkeeper Gloves",
                            Price = 38.00m,
                            ProductTypeId = 8,
                            Quantity = 180,
                            Size = "S, M, L",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "300"
                        },
                        new
                        {
                            Id = 38,
                            Brand = "adidas",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 6, 9, 21, 46, 9, 43, DateTimeKind.Local).AddTicks(9037),
                            Description = "Designed to complement your everyday look, this adidas shoulder bag offers sleek, effortless style. Featuring a clean, minimalist design with an embossed Trefoil logo and refined outline stitching, it holds your essentials with ease. The padded shoulder strap ensures all-day comfort wherever you go.",
                            Dimensions = "35x20x10 cm",
                            Fabric = "polyester",
                            Featured = true,
                            Name = "Outline Trefoil Shoulder Bag",
                            Price = 55.00m,
                            ProductTypeId = 7,
                            Quantity = 120,
                            Size = "One Size",
                            SoldQuantity = 0,
                            Status = 1,
                            Warranty = "12 months",
                            Weight = "600"
                        });
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.ProductDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDiscounts");
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 0,
                            ImagePath = "product_data/jerseys/manchesterunited/product1",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 0,
                            ImagePath = "product_data/jerseys/manchesterunited/product2",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 0,
                            ImagePath = "product_data/jerseys/manchesterunited/product3",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 0,
                            ImagePath = "product_data/jerseys/realmadrid/product1",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 0,
                            ImagePath = "product_data/jerseys/realmadrid/product2",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 0,
                            ImagePath = "product_data/jerseys/barcelona/product1",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 0,
                            ImagePath = "product_data/jerseys/barcelona/product2",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 0,
                            ImagePath = "product_data/jerseys/acmilan/product1",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 0,
                            ImagePath = "product_data/jerseys/acmilan/product2",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 0,
                            ImagePath = "product_data/jerseys/bayern/product1",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 0,
                            ImagePath = "product_data/jerseys/psg/product1",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 0,
                            ImagePath = "product_data/jerseys/intermilan/product1",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 0,
                            ImagePath = "product_data/jerseys/dortmund/product1",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 0,
                            ImagePath = "product_data/shoes/nike/product1",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 0,
                            ImagePath = "product_data/shoes/nike/product2",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 0,
                            ImagePath = "product_data/shoes/nike/product3",
                            ProductId = 16
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 0,
                            ImagePath = "product_data/shoes/adidas/product1",
                            ProductId = 17
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 0,
                            ImagePath = "product_data/shoes/adidas/product2",
                            ProductId = 18
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 0,
                            ImagePath = "product_data/shoes/adidas/product3",
                            ProductId = 19
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 0,
                            ImagePath = "product_data/shoes/adidas/product4",
                            ProductId = 20
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 0,
                            ImagePath = "product_data/shoes/adidas/product5",
                            ProductId = 21
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 0,
                            ImagePath = "product_data/jackets/machesterunited/product1",
                            ProductId = 22
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 0,
                            ImagePath = "product_data/jackets/machesterunited/product2",
                            ProductId = 23
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 0,
                            ImagePath = "product_data/jackets/acmilan/product1",
                            ProductId = 24
                        },
                        new
                        {
                            Id = 25,
                            DisplayOrder = 0,
                            ImagePath = "product_data/jackets/realmadrid/product1",
                            ProductId = 25
                        },
                        new
                        {
                            Id = 26,
                            DisplayOrder = 0,
                            ImagePath = "product_data/jackets/intermilan/product1",
                            ProductId = 26
                        },
                        new
                        {
                            Id = 27,
                            DisplayOrder = 0,
                            ImagePath = "product_data/jackets/psg/product1",
                            ProductId = 27
                        },
                        new
                        {
                            Id = 28,
                            DisplayOrder = 0,
                            ImagePath = "product_data/accessories/manchesterunited/product1",
                            ProductId = 28
                        },
                        new
                        {
                            Id = 29,
                            DisplayOrder = 0,
                            ImagePath = "product_data/accessories/manchesterunited/product2",
                            ProductId = 29
                        },
                        new
                        {
                            Id = 30,
                            DisplayOrder = 0,
                            ImagePath = "product_data/accessories/manchesterunited/product3",
                            ProductId = 30
                        },
                        new
                        {
                            Id = 31,
                            DisplayOrder = 0,
                            ImagePath = "product_data/accessories/manchesterunited/product4",
                            ProductId = 31
                        },
                        new
                        {
                            Id = 32,
                            DisplayOrder = 0,
                            ImagePath = "product_data/accessories/manchesterunited/product5",
                            ProductId = 32
                        },
                        new
                        {
                            Id = 33,
                            DisplayOrder = 0,
                            ImagePath = "product_data/accessories/manchesterunited/product6",
                            ProductId = 33
                        },
                        new
                        {
                            Id = 34,
                            DisplayOrder = 0,
                            ImagePath = "product_data/accessories/manchesterunited/product7",
                            ProductId = 34
                        },
                        new
                        {
                            Id = 35,
                            DisplayOrder = 0,
                            ImagePath = "product_data/accessories/adidas/product1",
                            ProductId = 35
                        },
                        new
                        {
                            Id = 36,
                            DisplayOrder = 0,
                            ImagePath = "product_data/accessories/adidas/product2",
                            ProductId = 36
                        },
                        new
                        {
                            Id = 37,
                            DisplayOrder = 0,
                            ImagePath = "product_data/accessories/adidas/product3",
                            ProductId = 37
                        },
                        new
                        {
                            Id = 38,
                            DisplayOrder = 0,
                            ImagePath = "product_data/accessories/adidas/product4",
                            ProductId = 38
                        });
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Football"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hat"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Toy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Scarf"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Book/Magazines"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gloves"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bag"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Running"
                        });
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CUSTOMER"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ADMIN"
                        },
                        new
                        {
                            Id = 3,
                            Name = "MANAGER"
                        });
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.Cart", b =>
                {
                    b.HasOne("CSE443_KTM_Ecommerce.Models.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("CSE443_KTM_Ecommerce.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.CartItem", b =>
                {
                    b.HasOne("CSE443_KTM_Ecommerce.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSE443_KTM_Ecommerce.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.Order", b =>
                {
                    b.HasOne("CSE443_KTM_Ecommerce.Models.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId");

                    b.HasOne("CSE443_KTM_Ecommerce.Models.Delivery", "Delivery")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSE443_KTM_Ecommerce.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Delivery");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.OrderItem", b =>
                {
                    b.HasOne("CSE443_KTM_Ecommerce.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSE443_KTM_Ecommerce.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.Payment", b =>
                {
                    b.HasOne("CSE443_KTM_Ecommerce.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("CSE443_KTM_Ecommerce.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.Product", b =>
                {
                    b.HasOne("CSE443_KTM_Ecommerce.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSE443_KTM_Ecommerce.Models.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.ProductDiscount", b =>
                {
                    b.HasOne("CSE443_KTM_Ecommerce.Models.Product", "Product")
                        .WithMany("ProductDiscounts")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.ProductImage", b =>
                {
                    b.HasOne("CSE443_KTM_Ecommerce.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("CSE443_KTM_Ecommerce.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSE443_KTM_Ecommerce.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.Delivery", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.Order", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.Product", b =>
                {
                    b.Navigation("ProductDiscounts");

                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CSE443_KTM_Ecommerce.Models.User", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
